name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] "
labels: ["enhancement", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide detailed information about your request.

  - type: textarea
    id: problem
    attributes:
      label: Problem or Use Case
      description: What problem does this feature solve? What use case does it address?
      placeholder: Describe the problem or use case this feature would address...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
      placeholder: Describe your proposed solution...
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component of the system would this affect?
      options:
        - Domain Layer (Business Logic)
        - Infrastructure Layer (Adapters)
        - YNAB Integration
        - Bank Integration
        - API/REST Layer
        - Architecture/Testing
        - Documentation
        - Other (specify below)
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve workflow
        - High - Critical for use case
        - Critical - Blocking current functionality
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions or features you've considered.
      placeholder: Alternative approaches you've considered...

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What would make this feature complete? How would you test it?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation Considerations
      description: Please check all that apply
      options:
        - label: This change maintains hexagonal architecture principles
        - label: This change includes comprehensive test coverage
        - label: This change is backwards compatible
        - label: I'm willing to contribute to the implementation

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples about the feature request.
      placeholder: Any additional information, mockups, or examples...